;;; Automatically generated by ‘recentf’ on Tue Jun 27 15:27:12 2023.

(setq recentf-list
      '(
        "/home/nhe/.config/emacs/custom.el"
        "/home/nhe/.config/emacs/init.el"
        "/home/nhe/.config/emacs/var/image-dired/db.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
