;;; Automatically generated by ‘recentf’ on Wed Jun 21 10:54:39 2023.

(setq recentf-list
      '(
        "/home/nhe/.config/emacs/init.el"
        "/home/nhe/emacs.txt"
        "/home/nhe/jon.txt"
        "/home/nhe/dronepy/main.py"
        "/home/nhe/.config/emacs/var/image-dired/db.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
